const SERVER_BASE_URL_DEVELOPMENT = 'https://localhost:7248';

const BASE_ENDPOINTS = {
    GET_ALL_PASSWORD_RECORDS: 'api/passwordrecords',
    CREATE_PASSWORD_RECORD: 'api/passwordrecords',
    TOGGLE_VISIBILITY: (id: number) => `api/passwordrecords/${id}/toggle-visibility`,
    SEARCH_PASSWORD_RECORDS: 'api/passwordrecords/search'
  };

  const DEVELOPMENT_ENDPOINTS = {
    GET_ALL_PASSWORD_RECORDS: `${SERVER_BASE_URL_DEVELOPMENT}/${BASE_ENDPOINTS.GET_ALL_PASSWORD_RECORDS}`,  
    CREATE_PASSWORD_RECORD: `${SERVER_BASE_URL_DEVELOPMENT}/${BASE_ENDPOINTS.CREATE_PASSWORD_RECORD}`,
    TOGGLE_VISIBILITY: (id: number) => `${SERVER_BASE_URL_DEVELOPMENT}/${BASE_ENDPOINTS.TOGGLE_VISIBILITY(id)}`,
    SEARCH_PASSWORD_RECORDS: `${SERVER_BASE_URL_DEVELOPMENT}/${BASE_ENDPOINTS.SEARCH_PASSWORD_RECORDS}`
  };

const ENDPOINTS_TO_EXPORT = DEVELOPMENT_ENDPOINTS;

export default ENDPOINTS_TO_EXPORT;